replicaCount: 1

image:
  name: homeassistant/home-assistant
  tag: "latest"

service:
  enabled: enabled
  type: ClusterIP
  port: 8123

storage:
  config:
    size: 10Gi

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "2Gi"

backup:
  tokenSecretName: homeassistant-token
  enabled: true

ingress:
  enabled: true
  host: "my.home.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
